### PR TITLE
Implemented stop, start and reboot operations for servers

### PR DESCRIPTION
**Pull request by mafraba**
Service requests implemented for 'powerOn', 'powerOff' and 'reboot' methods, on virtual and baremetal instances.

Model 'server' methods 'start', 'stop', 'shutdown' and 'reboot' implemented.

Refers to issue #39 .

### CODE REVIEW

**Comment by fernandes** [comment]
Hi @mafraba , thank you for your pull request.

Could you please implement the mock requests and add the tests before we merge?

Thank you!

**Comment by cphrmky** [comment]
@mafraba this is excellent thank very much!

Happy to merge this once we get mocks and tests as @fernandes mentioned.

Will also need quick signature on a copy of the CLA (and the CCLA if you're doing this for your employer on their time).  They can be found in the [docs/](https://github.com/fog/fog-softlayer/tree/master/docs) directory.

**Comment by mafraba** [comment]
Hi @fernandes , @cphrmky ,

Tests and mock requests implemented, and CLA and CCLA sent.

Cheers.

**Comment by fernandes** [comment]
hey @mafraba just looking at the code you did an amazing job... I'm gonna run the tests against the real softlayer API (I believe won't find any error once you probably tested, just to make sure) then I merge this PR late today :)

**Comment by cphrmky** [comment]
nice!

**Pull request merged**
