### PR TITLE
wait_for_id and fixedConfigurationPreset.

### PR DESCRIPTION
**Pull request by causton81**
Support quick provision bare metal using fixedConfigurationPreset.
Helper method to wait for id to be ready on bare metal order.

I have used this patch successfully with a personal version of chef-provisioning-fog with SoftLayer support.

### CODE REVIEW

**Comment by fernandes** [comment]
hi @causton81 

thank you for your contribution, we usually don't add external dependencies on fog providers, could you please tell what is the benefits using `retryable` so we can try to improve the gem without adding this dep.

**Comment by causton81** [comment]
@fernandes 

retryable just provides a convenient way of executing a block some number of times with a delay between tries.  I think it could easily be replaced with a loop and sleep.

**Comment by causton81** [comment]
@fernandes so what are next steps?

**Comment by fernandes** [comment]
hi @causton, sorry about long delay,

on cloud server we use a [wait_for](https://github.com/fog/fog-softlayer/blob/master/lib/fog/softlayer/models/compute/server.rb#L177), would you mind try to use this method instead of add `retryable`?

if `wait_for` works, we fix the build and are ready to :shipit: :sunglasses:

**Comment by causton81** [comment]
I updated to use Fog.wait_for. Fog.Model.wait_for calls reload which requires the id which isn't available immediately.

**Comment by cphrmky** [comment]
@causton81 this looks pretty great, thanks for sending this in

can you amend `examples/compute.md` with a couple of lines that show how to use this and the expected result?

With that in place place I'm happy to merge it and cut a new release so that you're unblocked on chef-provisioning-fog.

**Comment by cphrmky** [comment]
@causton81 also, I just updated the .travis.yml which should fix the errored build, if you want to `git rebase master` it should build cleanly when you next push.

**Comment by cphrmky** [comment]
Looked this over, tested it out, it works as advertised, going to merge now and I'll add the updates to `examples/compute.md`

**Comment by cphrmky** [comment]
@causton81 this has been merged and v1.1.0 has been cut which includes this.

/cc @jjasghar

**Comment by jjasghar** [comment]
:metal:

**Pull request merged**
