### PR TITLE
Using Relative paths

### PR DESCRIPTION
**Pull request by plribeiro3000**
relates to fog/fog#3430

This is a huge diff but sounds like it did the trick. I'm opening this as a start point so we can discuss about it and find the best approach to tackle it.

The changes are:

* Use `autoload` so extra files only get loaded when needed
* Use relative paths
* Move the logic in the `fog/softlayer/core` file to the `fog/softlayer` since this is the only one bundler will load automatically.
* Remove some unnecessary requires in the models
* Move some files so the path will match the namespace

### CODE REVIEW

**Comment by cphrmky** [comment]
@plribeiro3000 this looks pretty good to me.  It appears to have passed all the formal tests.  I'm going to take it for a quick test drive since it's a pretty large diff as you said and if I don't find anything that doesn't seem right I'm happy to merge it.

**Comment by plribeiro3000** [comment]
@cphrmky Awesome. Let me know if anything seems wrong to you so i can fix. =)

**Comment by cphrmky** [comment]
All seems well from here.  Merging now, will cut a release later today.

**Comment by plribeiro3000** [comment]
Thank you @cphrmky ! :smile:

**Comment by plribeiro3000** [comment]
@cphrmky Did you get the chance to do a new release?

**Comment by fernandes** [comment]
@plribeiro3000 are you needing a new one? I can do it...

**Comment by plribeiro3000** [comment]
Yeah. We are looking to fix fog/fog#3430 and my last PR here addressed part of the issue.

It would be awesome if you could do a release for it. Thanks!

**Comment by fernandes** [comment]
@plribeiro3000 released a new one (0.4.2) ;)

**Comment by plribeiro3000** [comment]
Thx @fernandes. I'm already tracking down the usage of `autoload` and another solutions to replace it in case it is removed from ruby. But until that happens this fix is enough. Thanks!

**Comment by fernandes** [comment]
thats great... thank you!

**Pull request merged**
